const { Client, Intents } = require('discord.js');
const fs = require('fs');
const path = require('path');
const config = require('./config');

const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES] });

// Logging
function log(log) {
  const currentDate = new Date();
  const logFilePath = path.join(`log/log-${currentDate.toISOString().split('T')[0]}.txt`);
  fs.appendFileSync(logFilePath, `${log}\n`);
}

client.once("ready", async () => {
  try {
    const logMessage = `[${new Date().toLocaleString()}] Ready`;
    console.log(logMessage);
    log(logMessage);

    setInterval(() => {
      client.user.setActivity({
        name: `Create invite link! | ${client.ws.ping}ms | ${client.guilds.cache.size}Servers`
      });
    }, 10000); // 10秒ごとにアクティビティを更新

    // スラッシュコマンド一覧
    const commands = [
      {
        name: 'invite',
        description: '指定の条件で招待リンクを生成します。',
        options: [
          {
            name: 'expire',
            description: '有効期限を選択してください。',
            type: 'STRING',
            choices: [
              { name: '30分', value: '1800' },
              { name: '1時間', value: '3600' },
              { name: '6時間', value: '21600' },
              { name: '12時間', value: '43200' },
              { name: '1日', value: '86400' },
              { name: '7日', value: '604800' },
              { name: '制限なし', value: '0' },
            ],
            required: true,
          },
          {
            name: 'uses',
            description: '最大使用数を選択してください。',
            type: 'STRING',
            choices: [
              { name: '1回', value: '1' },
              { name: '5回', value: '5' },
              { name: '10回', value: '10' },
              { name: '25回', value: '25' },
              { name: '50回', value: '50' },
              { name: '100回', value: '100' },
              { name: '制限なし', value: '0' },
            ],
            required: true,
          },
          {
            name: 'channel',
            description: '招待リンクを作成するチャンネルを指定してください。',
            type: 'CHANNEL',
            required: true,
          },
        ],
      },
      {
        name: "ping",
        description: "Ping値を表示します。BOTの動作確認などにご使用ください。",
      }
    ];

    await client.application.commands.set(commands);

    const successfully = `[${new Date().toLocaleString()}] Slash commands registered successfully`;
    console.log(successfully);
    log(successfully);
  } catch (error) {
    const Error = `[${new Date().toLocaleString()}] Error: ${error.message}`;
    console.error(Error);
    log(Error);
  }
});


client.on("interactionCreate", async (interaction) => {
  if (!interaction.isCommand()) {
    return;
  }

  // ping
  if (interaction.commandName === "ping") {
    try {
      await interaction.deferReply({ ephemeral: true });
      const ping = client.ws.ping;

      const logMessage = (`[${new Date().toLocaleString()}] Slash commands: ping, Ping: ${ping}ms, User: ${interaction.user.tag} (ID: ${interaction.user.id}), Server: ${interaction.guild?.name || 'DM'}`);
      console.log(logMessage);
      log(logMessage);

      await interaction.followUp({
        content: `Ping: ${ping}ms`, ephemeral: true
      });
    } catch (error) {
      const logMessage = `[${new Date().toLocaleString()}] Error: ${error.message}`;
      console.log(logMessage);
      log(logMessage);
      await interaction.followUp({ content: `Error: ${error.message}`, ephemeral: true });
    }
  }

  // invite
  if (interaction.commandName === "invite") {
    try {
      await interaction.deferReply({ ephemeral: true });

      const expire = interaction.options.getString('expire');
      const uses = interaction.options.getString('uses');
      const channel = interaction.options.getChannel('channel') || interaction.channel;

      if (!channel || (channel.type !== 'GUILD_TEXT')) {
        await interaction.followUp({
          content: '指定されたチャンネルはテキストチャンネルではありません。',
          ephemeral: true,
        });
        const logMessage = `[${new Date().toLocaleString()}] Error: not text channel, Slash commands: invite, User: ${interaction.user.tag} (ID: ${interaction.user.id}), Server: ${interaction.guild?.name || 'DM'}`;
        console.log(logMessage);
        log(logMessage);
        return;
      }

      //招待リンク生成
      const invite = await channel.createInvite({
        temporary: false,
        maxAge: expire === '0' ? 0 : parseInt(expire),
        maxUses: uses === '0' ? 0 : parseInt(uses),
        unique: true,
        reason: 'Generated by /invite',
      });

      const logMessage = `[${new Date().toLocaleString()}] Slash commands: invite,  User: ${interaction.user.tag} (ID: ${interaction.user.id}), Server: ${interaction.guild?.name || 'DM'}`;
      console.log(logMessage);
      log(logMessage);

      await interaction.followUp({
        content: `招待リンクが生成されました: ${invite.url}`,
        ephemeral: true,
      });

    } catch (error) {
      const logMessage = `[${new Date().toLocaleString()}] Error: ${error.message}`;
      console.log(logMessage);
      log(logMessage);
      await interaction.followUp({ content: `Error: ${error.message}`, ephemeral: true });
    }
  }
});


client.login(config.token);
